baseURL = 'https://endemics.github.io/'
languageCode = 'en-gbh'
title = 'Endemics blog'
theme = 'PaperMod'
contentDir = 'content'
publishDir = 'public'

enableEmoji = true

[params]
  author = "Gildas Le Nadan"
